var eggPrice=10;
var eggQuantity=20;
var potatoPrice=30;
var potatoQuantity=3;
var eggTotal=eggPrice*eggQuantity;
var potatoTotal=potatoPrice*potatoQuantity;
var totalPrice=eggTotal+potatoTotal;
console.log(eggTotal);
console.log(potatoTotal);
console.log(totalPrice);